# Generated by Django 3.0.2 on 2020-02-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conjugation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('he_past', models.CharField(max_length=500)),
                ('she_past', models.CharField(max_length=500)),
                ('you_male_past', models.CharField(max_length=500)),
                ('you_female_past', models.CharField(max_length=500)),
                ('i_past', models.CharField(max_length=500)),
                ('we_past', models.CharField(max_length=500)),
                ('he_present', models.CharField(max_length=500)),
                ('she_present', models.CharField(max_length=500)),
                ('you_male_present', models.CharField(max_length=500)),
                ('you_female_present', models.CharField(max_length=500)),
                ('i_present', models.CharField(max_length=500)),
                ('we_present', models.CharField(max_length=500)),
                ('he_future', models.CharField(max_length=500)),
                ('she_future', models.CharField(max_length=500)),
                ('you_male_future', models.CharField(max_length=500)),
                ('you_female_future', models.CharField(max_length=500)),
                ('i_future', models.CharField(max_length=500)),
                ('we_future', models.CharField(max_length=500)),
                ('meaning', models.CharField(max_length=500)),
                ('usage', models.CharField(max_length=500)),
                ('comment', models.CharField(max_length=500)),
            ],
        ),
    ]
