# Generated by Django 3.0.2 on 2020-02-19 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('level1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conjugation',
            name='he_future',
        ),
        migrations.RemoveField(
            model_name='conjugation',
            name='i_future',
        ),
        migrations.RemoveField(
            model_name='conjugation',
            name='she_future',
        ),
        migrations.RemoveField(
            model_name='conjugation',
            name='we_future',
        ),
        migrations.RemoveField(
            model_name='conjugation',
            name='you_female_future',
        ),
        migrations.RemoveField(
            model_name='conjugation',
            name='you_male_future',
        ),
    ]
